import '../styles/Textblock.css'

function Textblock() {
    return (
        <section>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            <p>
                Hello!
            </p>
            
        </section>
    )
}

export default Textblock;